// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NutriPlan.Infrastructure.Persistence;

#nullable disable

namespace NutriPlan.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NutriPlan.Domain.Entities.DailyMenu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DayNumber")
                        .HasColumnType("integer");

                    b.Property<Guid?>("MealPlanId")
                        .HasColumnType("uuid");

                    b.Property<double>("TargetCalories")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MealPlanId");

                    b.ToTable("daily_menus", (string)null);
                });

            modelBuilder.Entity("NutriPlan.Domain.Entities.FoodItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AllergenWarning")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAllergenic")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("food_items", (string)null);
                });

            modelBuilder.Entity("NutriPlan.Domain.Entities.MealEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DailyMenuId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FoodItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("MealType")
                        .HasColumnType("integer");

                    b.Property<double>("PortionGrams")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DailyMenuId");

                    b.HasIndex("FoodItemId");

                    b.ToTable("meal_entries", (string)null);
                });

            modelBuilder.Entity("NutriPlan.Domain.Entities.MealLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("ActualPortionGrams")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAdhered")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MealEntryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("meal_logs", (string)null);
                });

            modelBuilder.Entity("NutriPlan.Domain.Entities.MealPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("meal_plans", (string)null);
                });

            modelBuilder.Entity("NutriPlan.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasDiscriminator<int>("Role");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("NutriPlan.Domain.Entities.Client", b =>
                {
                    b.HasBaseType("NutriPlan.Domain.Entities.User");

                    b.Property<int>("ActivityLevel")
                        .HasColumnType("integer");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<Guid?>("AssignedNutritionistId")
                        .HasColumnType("uuid");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<double>("HeightCm")
                        .HasColumnType("double precision");

                    b.Property<double>("WeightKg")
                        .HasColumnType("double precision");

                    b.HasIndex("AssignedNutritionistId");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("NutriPlan.Domain.Entities.Nutritionist", b =>
                {
                    b.HasBaseType("NutriPlan.Domain.Entities.User");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("NutriPlan.Domain.Entities.DailyMenu", b =>
                {
                    b.HasOne("NutriPlan.Domain.Entities.MealPlan", null)
                        .WithMany("DailyMenus")
                        .HasForeignKey("MealPlanId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NutriPlan.Domain.Entities.FoodItem", b =>
                {
                    b.OwnsOne("NutriPlan.Domain.ValueObjects.NutrientProfile", "NutrientsPer100g", b1 =>
                        {
                            b1.Property<Guid>("FoodItemId")
                                .HasColumnType("uuid");

                            b1.Property<double>("CarbsGrams")
                                .HasColumnType("double precision")
                                .HasColumnName("carbs_g");

                            b1.Property<double>("FatGrams")
                                .HasColumnType("double precision")
                                .HasColumnName("fat_g");

                            b1.Property<double>("FiberGrams")
                                .HasColumnType("double precision")
                                .HasColumnName("fiber_g");

                            b1.Property<double>("ProteinGrams")
                                .HasColumnType("double precision")
                                .HasColumnName("protein_g");

                            b1.HasKey("FoodItemId");

                            b1.ToTable("food_items");

                            b1.WithOwner()
                                .HasForeignKey("FoodItemId");
                        });

                    b.Navigation("NutrientsPer100g")
                        .IsRequired();
                });

            modelBuilder.Entity("NutriPlan.Domain.Entities.MealEntry", b =>
                {
                    b.HasOne("NutriPlan.Domain.Entities.DailyMenu", null)
                        .WithMany("Entries")
                        .HasForeignKey("DailyMenuId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NutriPlan.Domain.Entities.FoodItem", "FoodItem")
                        .WithMany()
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FoodItem");
                });

            modelBuilder.Entity("NutriPlan.Domain.Entities.MealLog", b =>
                {
                    b.HasOne("NutriPlan.Domain.Entities.Client", null)
                        .WithMany("MealLogs")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NutriPlan.Domain.Entities.MealPlan", b =>
                {
                    b.HasOne("NutriPlan.Domain.Entities.Client", null)
                        .WithMany("MealPlans")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NutriPlan.Domain.Entities.Client", b =>
                {
                    b.HasOne("NutriPlan.Domain.Entities.Nutritionist", null)
                        .WithMany("AssignedClients")
                        .HasForeignKey("AssignedNutritionistId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("NutriPlan.Domain.Entities.DietaryGoal", "CurrentGoal", b1 =>
                        {
                            b1.Property<Guid>("ClientId")
                                .HasColumnType("uuid");

                            b1.Property<int>("GoalType")
                                .HasColumnType("integer")
                                .HasColumnName("goal_type");

                            b1.Property<DateTime>("TargetDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("goal_target_date");

                            b1.Property<double>("TargetWeightKg")
                                .HasColumnType("double precision")
                                .HasColumnName("goal_target_weight_kg");

                            b1.HasKey("ClientId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("ClientId");
                        });

                    b.Navigation("CurrentGoal");
                });

            modelBuilder.Entity("NutriPlan.Domain.Entities.DailyMenu", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("NutriPlan.Domain.Entities.MealPlan", b =>
                {
                    b.Navigation("DailyMenus");
                });

            modelBuilder.Entity("NutriPlan.Domain.Entities.Client", b =>
                {
                    b.Navigation("MealLogs");

                    b.Navigation("MealPlans");
                });

            modelBuilder.Entity("NutriPlan.Domain.Entities.Nutritionist", b =>
                {
                    b.Navigation("AssignedClients");
                });
#pragma warning restore 612, 618
        }
    }
}
